### ISSUE TITLE
Permission denied exception on first run

### ISSUE THREAD

**Issue by conorsch** [joedougherty/distractinator#1]
While running `distractd` for the first time, the script correctly identified the USB device:

```
Press enter to continue!
[0]: 
        Device: /dev/ttyACM0
        Manufacturer: Flora
        Hardware ID: USB VID:PID=239A:8004 LOCATION=2-2
```

But selecting it via `0` to continue raised a `serial.serialutil.SerialException`:

```
Select a port ('retry' if you still need to plug in the Distractinator(TM)): 0
[2016-12-03 16:10:18,111] INFO     custom_script variable not set in config file.
[2016-12-03 16:10:18,111] INFO     Attempting to find + connect to USB device...
[2016-12-03 16:10:18,117] INFO     Found device at address: /dev/ttyACM0
Traceback (most recent call last):
  File "/home/conor/.virtualenvs/distractinator/bin/distractd", line 9, in <module>
    load_entry_point('distractinator==0.2', 'console_scripts', 'distractd')()
  File "/home/conor/.virtualenvs/distractinator/local/lib/python2.7/site-packages/distractinator/__init__.py", line 4, in main
    d = Distractinator()
  File "/home/conor/.virtualenvs/distractinator/local/lib/python2.7/site-packages/distractinator/Distractinator.py", line 56, in __init__
    self.p = self.autoconnect() # Won't you join me on the perennial quest?
  File "/home/conor/.virtualenvs/distractinator/local/lib/python2.7/site-packages/distractinator/Distractinator.py", line 164, in autoconnect
    return serial.Serial(p.device, 9600, timeout=10)
  File "/home/conor/.virtualenvs/distractinator/local/lib/python2.7/site-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/home/conor/.virtualenvs/distractinator/local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
```

This was caused by default device permissions on Ubuntu 16.04 requiring special group membership:

```
$ ls -l /dev/ttyACM0
crw-rw---- 1 root dialout 166, 0 Dec  3 15:42 /dev/ttyACM0
```

Resolved it with:

```
$ sudo usermod -aG dialout $USER
$ newgrp dialout
```

Then reran the script and everything was hunky-dory. Would suggest two changes to help first-time users:

* [ ] Catch the `serial.serialutil.SerialException` and display an informative error message.
* [ ] Document the group membership tidbit in the README. (The target group may vary by platform, haven't tested widely.)

**Comment by joedougherty** [comment]
Closed by #7
